### PR TITLE
[Merged Stack b.0] Change to Pants Build

### PR DESCRIPTION
**Pull request by SimonBiggs**
This is a "preparatory PR" that is doing some of the initial restructure work in order to bring in the Pants build tooling. The repo structure is mimicking the following:

https://www.pantsbuild.org/docs/source-roots#srclang-setup

---

These moves still break CI, I will fix the CI in the stack above. If I pull in too many CI fixes in this PR it'll make this "move only PR" quite complicated. As such, I'll leave the PRs separate for now for simpler review, but prior to merging into main I'll group them up for the final merge.

---

This PR does the following:

- Moves `rai` and associated files into a subdirectory `src/python/rai/`
- Updates the CI to run within that subdirectory only for now
- Add in `raicontours` repo via a submodule

The only line of code changed is in the CI, to keep the CI passing with the move.

This move is to enable the one repo being able to be used to house multiple PyPI packages. The move is done separately from code changes so as to not introduce review complexity.

### CODE REVIEW

**Review by sjswerdloff — DISMISSED** [review]

**Comment by sjswerdloff** [comment]
But I have to admit I agree with PyLint on it's gripes.

**Comment by SimonBiggs** [comment]
> But I have to admit I agree with PyLint on it's gripes.

Hopefully all addressed by the time this stack is complete.

I was definitely struggling to work out how to implement a tooling change like this with minimal review pain...

**Comment by sjswerdloff** [comment]
> > But I have to admit I agree with PyLint on it's gripes.
> 
> Hopefully all addressed by the time this stack is complete.
> 
> I was definitely struggling to work out how to implement a tooling change like this with minimal review pain...

This approach is fine.
The intensive review comes when the tooling chain goes active.

**Comment by SimonBiggs** [comment]
Also, once the toolchain is passing CI I'll need to collapse this entire stack into this PR, as this PR can't actually merge into main without the CI passing.

Therefore there will be one final "approval" needed of a "monolith PR" that merges all this whole stack into one PR. But when I do that merge, I won't make any further changes from the individual stack items.

**Comment by SimonBiggs** [comment]
The only difference to this PR is that this is now all of those stacks merged (resulting in the approval to drop off).

No further changes were made.

**Pull request merged**
